// <auto-generated />
using System;
using Financio.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financio.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220921163735_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Financio.Core.Entities.Account", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Number");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Number = "0140",
                            Name = "Bank",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Number = "0740",
                            Name = "Eigenkapital",
                            RowVersion = new byte[0]
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
